### ISSUE TITLE
종목 리스트 HTTP 클라이언트 개발

### ISSUE THREAD

**Issue by SeungYeop-Han** [SeungYeop-Han/cosi#1]
### Mile Stone
🚩 [업비트 클라이언트 개발](https://github.com/users/SeungYeop-Han/projects/2/views/1?pane=issue&itemId=91290103)

### ToDo

- [x] 수신한 데이터를 저장할 DTO 클래스 ~~`CryptocurrencyPairSummary`~~ → `MarketInfo` 정의
  - [x] 미사용 필드 주석 처리(주석으로는 남겨 놓을 것)
- [x] 업비트 HTTP 클라이언트 개발: 종목 리스트 기능 구현
  - [x] 사용 기술 결정
  - [x]  gzip 압축 응답 디코딩
  - [x]  HTTP 캐싱 활용
- [x] 종목 리스트 내부 API 인터페이스 및 구현체 정의
  - [x]  폴링 방식으로 종목 리스트를 업데이트
  - [x]  필터링, 업비트에서 현재 거래 가능한 종목에 한정

**Comment by SeungYeop-Han** [comment]
### 사용 기술 결정

스프링의 `RestClient`를 이용하여 업비트 HTTP 클라이언트를 개발하기로 결정했습니다.

### 이유

- 현대적인 fluent API
- 비동기적으로 요청을 보낼 필요가 없음
- 스프링이 기존 RestTemplate 대신 밀어주고 있음
- 직렬화 및 역직렬화를 간편하게 수행할 수 있음

### RestClient 사용법 정리

[Spring RestClient](https://ammezkhan.notion.site/Spring-RestClient-122c43d953e88066a5a8e7f1b00308ce?pvs=4)

**Comment by SeungYeop-Han** [comment]
2024-12-20 15:19 업비트 HTTP 클라이언트 구현 완료

각 종목의 캔들 & 볼륨 시세 정보의 경우, 일단은 비공식 API를 사용하여 클라이언트에서 처리할 수 있는 것으로 보임
추후 이 부분을 다시 확인해서, 요청이 제한되는 경우 서버 측에서 확보해야 할 수도 있다. 
이 경우 #1 이슈를 다시 연 뒤 개발 진행하도록 할 계획
