### ISSUE TITLE
API 서버 예외 처리 계층 개발

### ISSUE THREAD

**Issue by SeungYeop-Han** [SeungYeop-Han/cosi#15]
API 요청을 처리하는 중 발생한 예외를 처리하고, 로그를 남기는 계층이 필요합니다.

###  요구 사항

- 예외 처리 계층은 API 종류(market, user, order, ...) 에 무관하게 재사용할 수 있어야 합니다.
- 에러 메시지는 공통된 형식을 가져야 합니다. 에러 메시지를 표현할 클래스가 필요합니다.
- 기본적으로 클라이언트 에러와 서버 에러로 나누어 처리해야 합니다.
  - 클라이언트 에러는 유효하지 않은 값을 입력하는 등, 클라이언트의 문제로 인해 정상적인 처리를 할 수 없는 경우 발생합니다.
  - 서버 에러는 클라이언트의 요청에 따라 정상적인 응답이 가능해야 하나, 서버의 내부적인 오류로 인하여 정상적으로 응답할 수 없는 경우 발생합니다.
- Spring Validation 을 사용합니다.
  - `MethodArgumentNotValidException` 예외에 대응할 수 있어야 합니다.
  - 필요한 경우 커스텀 validator 를 정의할 수 있습니다. 커스텀 validator 는 공통 예외 검증에 해당하는 경우에만 정의합니다. 예를 들어, 크기 또는 날짜의 선후 관계 등을 비교하거나 두 값의 동일성을 비교하는 등이 공통 예외 검증에 해당합니다.
  - 이 외에, 특수한 경우는 컨트롤러 또는 서비스 계층 등에서 처리하도록 합시다.
- 예외는 가급적 별도 클래스로 만들도록 합시다.

### ToDo

- [x] spring-boot-starter-validation 및 spring-boot-starter-logging 의존성 추가
- [x] com.cosi.api.exception 패키지 생성
- [x] `ErrorMessage` 클래스 정의
- [x] 클라이언트 에러(400 번대 에러)에 해당하는 `BadRequestException` 예외 클래스 정의
  > 서버 에러는 클라이언트 에러로 처리하지 못한 모든 에러를 서버 에러로 처리합니다. 따라서 서버 에러에 해당하는 예외 클래스는 별도로 정의하지 않습니다.
- [x] ExceptionHandler 클래스 정의
  > 발생한 예외의 유형에 따른 처리 로직을 해당 클래스에 작성합니다.

> [!NOTE]
필요할 때마다 BadRequestException 을 확장하는 예외 클래스를 정의하도록 하자
(ex. 종목 코드 없음 = MarketCodeNotFoundException ...)

**Comment by SeungYeop-Han** [comment]
테스트 클래스 위치만 살짝 이동시킴

**Comment by SeungYeop-Han** [comment]
스프링 MVC 컨트롤러 핸들러 메서드의 필수 파라미터가 전달되지 않은 경우 `MissingServletRequestParameterException` 예외가 발생합니다.

이 예외를 처리하는 예외 핸들러 메서드를 `ApiExceptionHandler` 에 추가해야 합니다.
