### ISSUE TITLE
현재가(Ticker) 웹소켓 클라이언트 개발

### ISSUE THREAD

**Issue by SeungYeop-Han** [SeungYeop-Han/cosi#2]
### Mile Stone
🚩 [업비트 클라이언트 개발](https://github.com/users/SeungYeop-Han/projects/2/views/1?pane=issue&itemId=91290103)

### ToDo

- [x] 수신한 데이터를 저장할 DTO 클래스 정의: `TickerRealtimeQuotes` & `TickerStatistic`

  > 역직렬화 비용과 cosi 클라이언트 네트워크 트래픽을 절약하기 위해서, 실시간 거래 정보(`TickerRealtime`)와 통계량(`TickerStatistic`)을 분리한다.

  - [x] `TickerRealtimeQuotes`: 실시간 시세 정보
    <details close>
    <summary>대상 필드</summary>

    - 종목 식별 코드
    - 현재가
    - 전일 대비 상승, 보합, 하락 여부
    - 전일 대비 변동 가격
    - 전일 대비 변동율
    - 매수 매도 구분
    
    </details>
  - [x] `TickerStatistic`: 통계량, 일정 기간 마다 주기적으로 갱신
    <details close>
    <summary>대상 필드</summary>

    - 종목 식별 코드
    - 당일 시가
    - 당일 고가
    - 당일 저가
    - 전일 종가
    - 금일 누적 거래량
    - 금일 누적 거래 대금
    - 누적 매도량
    - 누적 매수량
    - 24시간 누적 거래량
    - 24시간 누적 거래 대금
    - 52주 최고가
    - 52주 최고가 달성일
    - 52주 최저가
    - 52주 최저가 달성일
    - 거래 상태
    - 유의 여부
    
    </details>
  - [x] 미사용 필드 주석 처리

- [x] 사용 기술 결정
  - [x] 자바 웹소켓 구현체
  - [x] Gson vs Jackson

- [x] 현재가 정보 내부 API 인터페이스 및 구현체 정의

**Comment by SeungYeop-Han** [comment]
네트워크 트래픽을 절약하기 위해 업비트 공식 웹소켓 API로부터 응답 필드의 이름을 축약형으로 받습니다. (ex. `signedChangePrice` → `scp`).

**Comment by SeungYeop-Han** [comment]
### 자바 웹 소켓 구현체 결정

임시로 선택: [TooTallNate's java_websocket](https://github.com/TooTallNate/Java-WebSocket)

추후 테스트를 통해 웹 소켓 구현체 간 성능을 비교할 예정: #5

### Gson vs Jackson

임시: 일단은 사용법이 단순한 Gson 을 사용합니다.

추후 성능 비교 후 유의미한 차이가 있으면 Jackson으로 변경 예정: #6

**Comment by SeungYeop-Han** [comment]
업비트 웹 소켓 api 는 하나의 응답에 한 종목에 대한 정보만 포함한다는 사실을 간과했다. `TickerStatistics` 의 폴링 타이머를 각 종목 별로 만들어서 관리하도록 변경해야 한다. 종목 별 폴링 타이머를 Map 에 저장하는게 좋을 것 같다
